syntax = "proto3";

option java_multiple_files = true;
option java_package = "es.um.sisdist.backend.grpc";

package es.um.sisdist.backend.grpc;

service GrpcService
{
    rpc Ping(PingRequest) returns (PingResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc SendPrompt(PromptRequest) returns (PromptToken);
    rpc GetPromptResponse(PromptToken) returns (PromptResponse);
}

message PingRequest  { int32 v = 1; }
message PingResponse { int32 v = 1; }

message LoginRequest {
    string email = 1;
    string password = 2;
}

message LoginResponse {
    bool success = 1;
    string token = 2;
    UserMessage user = 3;
}

message UserMessage {
    string id = 1;
    string email = 2;
    string name = 3;
    int32 visits = 4;
}

message PromptRequest {
    string prompt = 1;
}

message PromptToken {
    string token = 1;
}

enum PromptStatus {
    STATUS_UNSPECIFIED = 0;
    PROCESSING = 1;
    READY = 2;
}

message PromptResponse {
    string response = 1;
    PromptStatus status = 2;
}
